name: 'Mini Kube Deploy Action'
description: 'Deploy PODs on local Minikube'
runs:
  using: 'composite'
  steps:
      - run: bash ${{ github.action_path }}/docker_build_push.sh
        shell: bash
        env:
          INPUT_CONSULURL: keyvalue
      - id: executing_shell
        run: bash ${{ github.action_path }}/k8s_deploy.sh
        shell: bash




