name: 'Deploy Action'
description: 'Build and Deploy PODs'
runs:
  using: 'composite'
  steps:
      - run: bash ${{ github.action_path }}/docker_build_push.sh
        shell: bash
      - id: executing_shell
        run: bash ${{ github.action_path }}/k8s_deploy.sh
        shell: bash




